# Generated by Django 5.0.6 on 2024-05-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serving', models.CharField(max_length=100)),
                ('calories', models.IntegerField()),
                ('food_type', models.CharField(choices=[('FRUIT', 'Fruit'), ('MEAT', 'Meat'), ('FOOD', 'Food'), ('VEGETABLE', 'Vegetable')], default='FOOD', max_length=10)),
                ('image', models.ImageField(upload_to='food_images/')),
            ],
        ),
    ]
