# Generated by Django 5.0.6 on 2024-05-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='food',
        ),
        migrations.AddField(
            model_name='cart',
            name='food',
            field=models.ManyToManyField(related_name='cart_items', to='pages.fooditem'),
        ),
    ]
