# Generated by Django 5.0.6 on 2024-05-14 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_cart_food_cart_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='food',
        ),
        migrations.AddField(
            model_name='cart',
            name='food',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='pages.fooditem'),
            preserve_default=False,
        ),
    ]
