# Generated by Django 5.0.6 on 2024-05-14 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_cart_food_cart_food'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
