# Generated by Django 5.0.6 on 2024-05-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_rename_carts_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='gram',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
